#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : efivar
Version  : 37
Release  : 22
URL      : https://github.com/rhboot/efivar/releases/download/37/efivar-37.tar.bz2
Source0  : https://github.com/rhboot/efivar/releases/download/37/efivar-37.tar.bz2
Summary  : Tools to manage UEFI variables
Group    : Development/Tools
License  : LGPL-2.1
Requires: efivar-bin = %{version}-%{release}
Requires: efivar-lib = %{version}-%{release}
Requires: efivar-license = %{version}-%{release}
Requires: efivar-man = %{version}-%{release}
Patch1: build.patch
Patch2: 0001-Fix-symbol-versioning-to-use-symver-attribute-rather.patch
Patch3: 0002-Only-use-new-symbol-versioning-with-new-gcc.patch

%description
efivar provides a simple command line interface to the UEFI variable facility.

%package bin
Summary: bin components for the efivar package.
Group: Binaries
Requires: efivar-license = %{version}-%{release}

%description bin
bin components for the efivar package.


%package dev
Summary: dev components for the efivar package.
Group: Development
Requires: efivar-lib = %{version}-%{release}
Requires: efivar-bin = %{version}-%{release}
Provides: efivar-devel = %{version}-%{release}
Requires: efivar = %{version}-%{release}

%description dev
dev components for the efivar package.


%package lib
Summary: lib components for the efivar package.
Group: Libraries
Requires: efivar-license = %{version}-%{release}

%description lib
lib components for the efivar package.


%package license
Summary: license components for the efivar package.
Group: Default

%description license
license components for the efivar package.


%package man
Summary: man components for the efivar package.
Group: Default

%description man
man components for the efivar package.


%prep
%setup -q -n efivar-37
cd %{_builddir}/efivar-37
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1615954126
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1615954126
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/efivar
cp %{_builddir}/efivar-37/COPYING %{buildroot}/usr/share/package-licenses/efivar/960c191c13417c4d81f2aa4315b0d0e8ade42436
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/efivar

%files dev
%defattr(-,root,root,-)
/usr/include/efivar/efiboot-creator.h
/usr/include/efivar/efiboot-loadopt.h
/usr/include/efivar/efiboot.h
/usr/include/efivar/efivar-dp.h
/usr/include/efivar/efivar-guids.h
/usr/include/efivar/efivar.h
/usr/lib64/libefiboot.so
/usr/lib64/libefivar.so
/usr/lib64/pkgconfig/efiboot.pc
/usr/lib64/pkgconfig/efivar.pc
/usr/share/man/man3/efi_append_variable.3
/usr/share/man/man3/efi_del_variable.3
/usr/share/man/man3/efi_get_next_variable_name.3
/usr/share/man/man3/efi_get_variable.3
/usr/share/man/man3/efi_get_variable_attributes.3
/usr/share/man/man3/efi_get_variable_size.3
/usr/share/man/man3/efi_guid_to_id_guid.3
/usr/share/man/man3/efi_guid_to_name.3
/usr/share/man/man3/efi_guid_to_str.3
/usr/share/man/man3/efi_guid_to_symbol.3
/usr/share/man/man3/efi_name_to_guid.3
/usr/share/man/man3/efi_set_variable.3
/usr/share/man/man3/efi_str_to_guid.3
/usr/share/man/man3/efi_symbol_to_guid.3
/usr/share/man/man3/efi_variable_alloc.3
/usr/share/man/man3/efi_variable_export.3
/usr/share/man/man3/efi_variable_free.3
/usr/share/man/man3/efi_variable_get_attributes.3
/usr/share/man/man3/efi_variable_get_data.3
/usr/share/man/man3/efi_variable_get_guid.3
/usr/share/man/man3/efi_variable_get_name.3
/usr/share/man/man3/efi_variable_import.3
/usr/share/man/man3/efi_variable_realize.3
/usr/share/man/man3/efi_variable_set_attributes.3
/usr/share/man/man3/efi_variable_set_data.3
/usr/share/man/man3/efi_variable_set_guid.3
/usr/share/man/man3/efi_variable_set_name.3
/usr/share/man/man3/efi_variable_t.3
/usr/share/man/man3/efi_variables_supported.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libefiboot.so.1
/usr/lib64/libefiboot.so.1.37
/usr/lib64/libefivar.so.1
/usr/lib64/libefivar.so.1.37

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/efivar/960c191c13417c4d81f2aa4315b0d0e8ade42436

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/efivar.1
