#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : efivar
Version  : 35
Release  : 13
URL      : https://github.com/rhboot/efivar/releases/download/35/efivar-35.tar.bz2
Source0  : https://github.com/rhboot/efivar/releases/download/35/efivar-35.tar.bz2
Summary  : Tools to manage UEFI variables
Group    : Development/Tools
License  : LGPL-2.1
Requires: efivar-bin
Requires: efivar-lib
Requires: efivar-doc

%description
efivar provides a simple command line interface to the UEFI variable facility.

%package bin
Summary: bin components for the efivar package.
Group: Binaries

%description bin
bin components for the efivar package.


%package dev
Summary: dev components for the efivar package.
Group: Development
Requires: efivar-lib
Requires: efivar-bin
Provides: efivar-devel

%description dev
dev components for the efivar package.


%package doc
Summary: doc components for the efivar package.
Group: Documentation

%description doc
doc components for the efivar package.


%package lib
Summary: lib components for the efivar package.
Group: Libraries

%description lib
lib components for the efivar package.


%prep
%setup -q -n efivar-35

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525540400
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1525540400
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/efivar

%files dev
%defattr(-,root,root,-)
/usr/include/efivar/efiboot-creator.h
/usr/include/efivar/efiboot-loadopt.h
/usr/include/efivar/efiboot.h
/usr/include/efivar/efivar-dp.h
/usr/include/efivar/efivar-guids.h
/usr/include/efivar/efivar.h
/usr/lib64/libefiboot.so
/usr/lib64/libefivar.so
/usr/lib64/pkgconfig/efiboot.pc
/usr/lib64/pkgconfig/efivar.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libefiboot.so.1
/usr/lib64/libefiboot.so.1.35
/usr/lib64/libefivar.so.1
/usr/lib64/libefivar.so.1.35
